language: node_js
node_js:
  - "6"
script:
  - npm run-script coverage
  - npm run-script lint
after_script: "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/coveralls/bin/coveralls.js"
